/* config-file-reader.c generated by valac 0.14.2, the Vala compiler
 * generated from config-file-reader.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>
#include <json-glib/json-glib.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define RUI_TYPE_CONFIG_FILE_READER (rui_config_file_reader_get_type ())
#define RUI_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReader))
#define RUI_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))
#define RUI_IS_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_IS_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_CONFIG_FILE_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))

typedef struct _RUIConfigFileReader RUIConfigFileReader;
typedef struct _RUIConfigFileReaderClass RUIConfigFileReaderClass;
typedef struct _RUIConfigFileReaderPrivate RUIConfigFileReaderPrivate;

#define RUI_TYPE_REMOTE_UI (rui_remote_ui_get_type ())

#define RUI_TYPE_PROTOCOL (rui_protocol_get_type ())
typedef struct _RUIProtocol RUIProtocol;

#define RUI_TYPE_ICON (rui_icon_get_type ())
typedef struct _RUIIcon RUIIcon;
typedef struct _RUIRemoteUI RUIRemoteUI;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_JsonObject_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonObject_free (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define __vala_JsonArray_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonArray_free (var), NULL)))
#define _rui_remote_ui_free0(var) ((var == NULL) ? NULL : (var = (rui_remote_ui_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _RUIParamSpecConfigFileReader RUIParamSpecConfigFileReader;

struct _RUIConfigFileReader {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RUIConfigFileReaderPrivate * priv;
};

struct _RUIConfigFileReaderClass {
	GTypeClass parent_class;
	void (*finalize) (RUIConfigFileReader *self);
};

struct _RUIProtocol {
	gchar** urls;
	gint urls_length1;
	gchar* shortName;
};

struct _RUIIcon {
	guint64* width;
	guint64* height;
	gchar* url;
};

struct _RUIRemoteUI {
	gchar* id;
	gchar* name;
	gchar* description;
	RUIProtocol* protocols;
	gint protocols_length1;
	RUIIcon* icons;
	gint icons_length1;
};

struct _RUIConfigFileReaderPrivate {
	gchar* _root_device_xml;
	gchar* _service_directory;
	gchar* config_file;
	GFileMonitor* file_monitor;
	GeeMap* _remoteUIs;
};

typedef enum  {
	RUI_ERROR_BAD_CONFIG
} RUIError;
#define RUI_ERROR rui_error_quark ()
struct _RUIParamSpecConfigFileReader {
	GParamSpec parent_instance;
};


static gpointer rui_config_file_reader_parent_class = NULL;

gpointer rui_config_file_reader_ref (gpointer instance);
void rui_config_file_reader_unref (gpointer instance);
GParamSpec* rui_param_spec_config_file_reader (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rui_value_set_config_file_reader (GValue* value, gpointer v_object);
void rui_value_take_config_file_reader (GValue* value, gpointer v_object);
gpointer rui_value_get_config_file_reader (const GValue* value);
GType rui_config_file_reader_get_type (void) G_GNUC_CONST;
GType rui_remote_ui_get_type (void) G_GNUC_CONST;
GType rui_protocol_get_type (void) G_GNUC_CONST;
RUIProtocol* rui_protocol_dup (const RUIProtocol* self);
void rui_protocol_free (RUIProtocol* self);
void rui_protocol_copy (const RUIProtocol* self, RUIProtocol* dest);
void rui_protocol_destroy (RUIProtocol* self);
GType rui_icon_get_type (void) G_GNUC_CONST;
RUIIcon* rui_icon_dup (const RUIIcon* self);
void rui_icon_free (RUIIcon* self);
void rui_icon_copy (const RUIIcon* self, RUIIcon* dest);
void rui_icon_destroy (RUIIcon* self);
RUIRemoteUI* rui_remote_ui_dup (const RUIRemoteUI* self);
void rui_remote_ui_free (RUIRemoteUI* self);
void rui_remote_ui_copy (const RUIRemoteUI* self, RUIRemoteUI* dest);
void rui_remote_ui_destroy (RUIRemoteUI* self);
#define RUI_CONFIG_FILE_READER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderPrivate))
enum  {
	RUI_CONFIG_FILE_READER_DUMMY_PROPERTY
};
RUIConfigFileReader* rui_config_file_reader_new (const gchar* config_file);
RUIConfigFileReader* rui_config_file_reader_construct (GType object_type, const gchar* config_file);
static gboolean rui_config_file_reader_check_required_members (RUIConfigFileReader* self, const gchar* type, JsonObject* obj, gchar** required_members, int required_members_length1);
void rui_config_file_reader_parse_config_file (RUIConfigFileReader* self, GError** error);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static JsonObject* _vala_JsonObject_copy (JsonObject* self);
GQuark rui_error_quark (void);
static void _vala_JsonObject_free (JsonObject* self);
static void _vala_JsonNode_free (JsonNode* self);
static void rui_config_file_reader_set_root_device_xml (RUIConfigFileReader* self, const gchar* value);
static void rui_config_file_reader_set_service_directory (RUIConfigFileReader* self, const gchar* value);
const gchar* rui_config_file_reader_get_service_directory (RUIConfigFileReader* self);
static JsonArray* _vala_JsonArray_copy (JsonArray* self);
static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_JsonArray_free (JsonArray* self);
static gchar** _vala_array_dup1 (gchar** self, int length);
static void _vala_array_add2 (RUIProtocol** array, int* length, int* size, const RUIProtocol* value);
static void _vala_RUIProtocol_array_free (RUIProtocol* array, gint array_length);
static RUIProtocol* _vala_array_dup2 (RUIProtocol* self, int length);
static guint64* _uint64_dup (guint64* self);
static void _vala_array_add3 (RUIIcon** array, int* length, int* size, const RUIIcon* value);
static void _vala_RUIIcon_array_free (RUIIcon* array, gint array_length);
static RUIIcon* _vala_array_dup3 (RUIIcon* self, int length);
GeeCollection* rui_config_file_reader_get_remoteUIs (RUIConfigFileReader* self);
static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value);
void rui_config_file_reader_watch_config_file (RUIConfigFileReader* self, GError** error);
static void rui_config_file_reader_on_config_file_changed (RUIConfigFileReader* self, GFile* file, GFile* other_file, GFileMonitorEvent event);
static void _rui_config_file_reader_on_config_file_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
const gchar* rui_config_file_reader_get_root_device_xml (RUIConfigFileReader* self);
static void g_cclosure_user_marshal_VOID__BOXED_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void rui_config_file_reader_finalize (RUIConfigFileReader* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


RUIConfigFileReader* rui_config_file_reader_construct (GType object_type, const gchar* config_file) {
	RUIConfigFileReader* self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (config_file != NULL, NULL);
	self = (RUIConfigFileReader*) g_type_create_instance (object_type);
	_tmp0_ = config_file;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->config_file);
	self->priv->config_file = _tmp1_;
	return self;
}


RUIConfigFileReader* rui_config_file_reader_new (const gchar* config_file) {
	return rui_config_file_reader_construct (RUI_TYPE_CONFIG_FILE_READER, config_file);
}


static gboolean rui_config_file_reader_check_required_members (RUIConfigFileReader* self, const gchar* type, JsonObject* obj, gchar** required_members, int required_members_length1) {
	gboolean result = FALSE;
	gboolean missing_required;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gboolean _tmp8_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (type != NULL, FALSE);
	g_return_val_if_fail (obj != NULL, FALSE);
	missing_required = FALSE;
	_tmp0_ = required_members;
	_tmp0__length1 = required_members_length1;
	{
		gchar** member_collection = NULL;
		gint member_collection_length1 = 0;
		gint _member_collection_size_ = 0;
		gint member_it = 0;
		member_collection = _tmp0_;
		member_collection_length1 = _tmp0__length1;
		for (member_it = 0; member_it < _tmp0__length1; member_it = member_it + 1) {
			gchar* _tmp1_;
			gchar* member = NULL;
			_tmp1_ = g_strdup (member_collection[member_it]);
			member = _tmp1_;
			{
				JsonObject* _tmp2_;
				const gchar* _tmp3_;
				gboolean _tmp4_ = FALSE;
				_tmp2_ = obj;
				_tmp3_ = member;
				_tmp4_ = json_object_has_member (_tmp2_, _tmp3_);
				if (!_tmp4_) {
					FILE* _tmp5_;
					const gchar* _tmp6_;
					const gchar* _tmp7_;
					_tmp5_ = stderr;
					_tmp6_ = type;
					_tmp7_ = member;
					fprintf (_tmp5_, "Ignoring %s with missing required attribute \"%s\".\n", _tmp6_, _tmp7_);
					missing_required = TRUE;
				}
				_g_free0 (member);
			}
		}
	}
	_tmp8_ = missing_required;
	result = !_tmp8_;
	return result;
}


static JsonNode* _vala_JsonNode_copy (JsonNode* self) {
	return g_boxed_copy (json_node_get_type (), self);
}


static gpointer __vala_JsonNode_copy0 (gpointer self) {
	return self ? _vala_JsonNode_copy (self) : NULL;
}


static JsonObject* _vala_JsonObject_copy (JsonObject* self) {
	return g_boxed_copy (json_object_get_type (), self);
}


static gpointer __vala_JsonObject_copy0 (gpointer self) {
	return self ? _vala_JsonObject_copy (self) : NULL;
}


static void _vala_JsonObject_free (JsonObject* self) {
	g_boxed_free (json_object_get_type (), self);
}


static void _vala_JsonNode_free (JsonNode* self) {
	g_boxed_free (json_node_get_type (), self);
}


static JsonArray* _vala_JsonArray_copy (JsonArray* self) {
	return g_boxed_copy (json_array_get_type (), self);
}


static gpointer __vala_JsonArray_copy0 (gpointer self) {
	return self ? _vala_JsonArray_copy (self) : NULL;
}


static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_JsonArray_free (JsonArray* self) {
	g_boxed_free (json_array_get_type (), self);
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static void _vala_array_add2 (RUIProtocol** array, int* length, int* size, const RUIProtocol* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (RUIProtocol, *array, *size);
	}
	(*array)[(*length)++] = *value;
}


static void _vala_RUIProtocol_array_free (RUIProtocol* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			rui_protocol_destroy (&array[i]);
		}
	}
	g_free (array);
}


static RUIProtocol* _vala_array_dup2 (RUIProtocol* self, int length) {
	RUIProtocol* result;
	int i;
	result = g_new0 (RUIProtocol, length);
	for (i = 0; i < length; i++) {
		RUIProtocol _tmp0_ = {0};
		rui_protocol_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


static guint64* _uint64_dup (guint64* self) {
	guint64* dup;
	dup = g_new0 (guint64, 1);
	memcpy (dup, self, sizeof (guint64));
	return dup;
}


static gpointer __uint64_dup0 (gpointer self) {
	return self ? _uint64_dup (self) : NULL;
}


static void _vala_array_add3 (RUIIcon** array, int* length, int* size, const RUIIcon* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (RUIIcon, *array, *size);
	}
	(*array)[(*length)++] = *value;
}


static void _vala_RUIIcon_array_free (RUIIcon* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			rui_icon_destroy (&array[i]);
		}
	}
	g_free (array);
}


static RUIIcon* _vala_array_dup3 (RUIIcon* self, int length) {
	RUIIcon* result;
	int i;
	result = g_new0 (RUIIcon, length);
	for (i = 0; i < length; i++) {
		RUIIcon _tmp0_ = {0};
		rui_icon_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void rui_config_file_reader_parse_config_file (RUIConfigFileReader* self, GError** error) {
	JsonParser* _tmp0_;
	JsonParser* parser;
	JsonParser* _tmp1_;
	const gchar* _tmp2_;
	JsonParser* _tmp3_;
	JsonNode* _tmp4_ = NULL;
	JsonNode* _tmp5_;
	JsonNode* root;
	JsonNode* _tmp6_;
	JsonObject* _tmp7_ = NULL;
	JsonObject* _tmp8_;
	JsonObject* object;
	JsonObject* _tmp9_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar** _tmp13_ = NULL;
	gchar** required_members;
	gint required_members_length1;
	gint _required_members_size_;
	JsonObject* _tmp14_;
	gchar** _tmp15_;
	gint _tmp15__length1;
	gboolean _tmp16_ = FALSE;
	JsonObject* _tmp18_;
	const gchar* _tmp19_ = NULL;
	JsonObject* _tmp20_;
	const gchar* _tmp21_ = NULL;
	const gchar* _tmp22_;
	gboolean _tmp23_ = FALSE;
	JsonObject* _tmp30_;
	JsonArray* _tmp31_ = NULL;
	JsonArray* _tmp32_;
	JsonArray* uis;
	GeeHashMap* _tmp33_;
	GeeHashMap* remoteUIs;
	gchar** _tmp188_ = NULL;
	gchar** changed_uis;
	gint changed_uis_length1;
	gint _changed_uis_size_;
	GeeHashMap* _tmp223_;
	GeeMap* _tmp224_;
	gchar** _tmp225_;
	gint _tmp225__length1;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = json_parser_new ();
	parser = _tmp0_;
	_tmp1_ = parser;
	_tmp2_ = self->priv->config_file;
	json_parser_load_from_file (_tmp1_, _tmp2_, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (parser);
		return;
	}
	_tmp3_ = parser;
	_tmp4_ = json_parser_get_root (_tmp3_);
	_tmp5_ = __vala_JsonNode_copy0 (_tmp4_);
	root = _tmp5_;
	_tmp6_ = root;
	_tmp7_ = json_node_get_object (_tmp6_);
	_tmp8_ = __vala_JsonObject_copy0 (_tmp7_);
	object = _tmp8_;
	_tmp9_ = object;
	if (_tmp9_ == NULL) {
		GError* _tmp10_;
		_tmp10_ = g_error_new_literal (RUI_ERROR, RUI_ERROR_BAD_CONFIG, "Config file has no root object.\n");
		_inner_error_ = _tmp10_;
		g_propagate_error (error, _inner_error_);
		__vala_JsonObject_free0 (object);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
		return;
	}
	_tmp11_ = g_strdup ("root-device-xml");
	_tmp12_ = g_strdup ("service-directory");
	_tmp13_ = g_new0 (gchar*, 2 + 1);
	_tmp13_[0] = _tmp11_;
	_tmp13_[1] = _tmp12_;
	required_members = _tmp13_;
	required_members_length1 = 2;
	_required_members_size_ = required_members_length1;
	_tmp14_ = object;
	_tmp15_ = required_members;
	_tmp15__length1 = required_members_length1;
	_tmp16_ = rui_config_file_reader_check_required_members (self, "config file", _tmp14_, _tmp15_, _tmp15__length1);
	if (!_tmp16_) {
		GError* _tmp17_;
		_tmp17_ = g_error_new_literal (RUI_ERROR, RUI_ERROR_BAD_CONFIG, "Missing \"root-device-xml\" or \"service-directory\"");
		_inner_error_ = _tmp17_;
		g_propagate_error (error, _inner_error_);
		required_members = (_vala_array_free (required_members, required_members_length1, (GDestroyNotify) g_free), NULL);
		__vala_JsonObject_free0 (object);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
		return;
	}
	_tmp18_ = object;
	_tmp19_ = json_object_get_string_member (_tmp18_, "root-device-xml");
	rui_config_file_reader_set_root_device_xml (self, _tmp19_);
	_tmp20_ = object;
	_tmp21_ = json_object_get_string_member (_tmp20_, "service-directory");
	rui_config_file_reader_set_service_directory (self, _tmp21_);
	_tmp22_ = self->priv->_service_directory;
	_tmp23_ = g_path_is_absolute (_tmp22_);
	if (!_tmp23_) {
		const gchar* _tmp24_;
		gchar* _tmp25_ = NULL;
		gchar* _tmp26_;
		const gchar* _tmp27_;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_;
		_tmp24_ = self->priv->config_file;
		_tmp25_ = g_path_get_dirname (_tmp24_);
		_tmp26_ = _tmp25_;
		_tmp27_ = self->priv->_service_directory;
		_tmp28_ = g_build_filename (_tmp26_, _tmp27_, NULL);
		_tmp29_ = _tmp28_;
		rui_config_file_reader_set_service_directory (self, _tmp29_);
		_g_free0 (_tmp29_);
		_g_free0 (_tmp26_);
	}
	_tmp30_ = object;
	_tmp31_ = json_object_get_array_member (_tmp30_, "uis");
	_tmp32_ = __vala_JsonArray_copy0 (_tmp31_);
	uis = _tmp32_;
	_tmp33_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, RUI_TYPE_REMOTE_UI, (GBoxedCopyFunc) rui_remote_ui_dup, rui_remote_ui_free, NULL, NULL, NULL);
	remoteUIs = _tmp33_;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp34_;
			_tmp34_ = TRUE;
			while (TRUE) {
				gboolean _tmp35_;
				gint _tmp37_;
				JsonArray* _tmp38_;
				guint _tmp39_ = 0U;
				JsonArray* _tmp40_;
				gint _tmp41_;
				JsonNode* _tmp42_ = NULL;
				JsonObject* _tmp43_ = NULL;
				JsonObject* _tmp44_;
				JsonObject* ui_node;
				JsonObject* _tmp45_;
				gchar* _tmp47_;
				gchar* _tmp48_;
				gchar* _tmp49_;
				gchar** _tmp50_ = NULL;
				JsonObject* _tmp51_;
				gchar** _tmp52_;
				gint _tmp52__length1;
				gboolean _tmp53_ = FALSE;
				JsonObject* _tmp54_;
				const gchar* _tmp55_ = NULL;
				gchar* _tmp56_;
				JsonObject* _tmp57_;
				const gchar* _tmp58_ = NULL;
				gchar* _tmp59_;
				RUIRemoteUI _tmp60_ = {0};
				RUIRemoteUI remoteUI;
				GeeHashMap* _tmp61_;
				RUIRemoteUI _tmp62_;
				const gchar* _tmp63_;
				gboolean _tmp64_ = FALSE;
				JsonObject* _tmp68_;
				gboolean _tmp69_ = FALSE;
				RUIProtocol* _tmp73_ = NULL;
				RUIProtocol* protocols;
				gint protocols_length1;
				gint _protocols_size_;
				JsonObject* _tmp74_;
				JsonArray* _tmp75_ = NULL;
				JsonArray* _tmp76_;
				JsonArray* protocols_node;
				RUIProtocol* _tmp121_;
				gint _tmp121__length1;
				RUIProtocol* _tmp123_;
				gint _tmp123__length1;
				RUIProtocol* _tmp124_;
				gint _tmp124__length1;
				JsonObject* _tmp125_;
				gboolean _tmp126_ = FALSE;
				GeeHashMap* _tmp184_;
				RUIRemoteUI _tmp185_;
				const gchar* _tmp186_;
				RUIRemoteUI _tmp187_;
				_tmp35_ = _tmp34_;
				if (!_tmp35_) {
					gint _tmp36_;
					_tmp36_ = i;
					i = _tmp36_ + 1;
				}
				_tmp34_ = FALSE;
				_tmp37_ = i;
				_tmp38_ = uis;
				_tmp39_ = json_array_get_length (_tmp38_);
				if (!(((guint) _tmp37_) < _tmp39_)) {
					break;
				}
				_tmp40_ = uis;
				_tmp41_ = i;
				_tmp42_ = json_array_get_element (_tmp40_, (guint) _tmp41_);
				_tmp43_ = json_node_get_object (_tmp42_);
				_tmp44_ = __vala_JsonObject_copy0 (_tmp43_);
				ui_node = _tmp44_;
				_tmp45_ = ui_node;
				if (_tmp45_ == NULL) {
					FILE* _tmp46_;
					_tmp46_ = stderr;
					fprintf (_tmp46_, "Ignoring non-object member of uis array.\n");
					__vala_JsonObject_free0 (ui_node);
					continue;
				}
				_tmp47_ = g_strdup ("id");
				_tmp48_ = g_strdup ("name");
				_tmp49_ = g_strdup ("protocols");
				_tmp50_ = g_new0 (gchar*, 3 + 1);
				_tmp50_[0] = _tmp47_;
				_tmp50_[1] = _tmp48_;
				_tmp50_[2] = _tmp49_;
				required_members = (_vala_array_free (required_members, required_members_length1, (GDestroyNotify) g_free), NULL);
				required_members = _tmp50_;
				required_members_length1 = 3;
				_required_members_size_ = required_members_length1;
				_tmp51_ = ui_node;
				_tmp52_ = required_members;
				_tmp52__length1 = required_members_length1;
				_tmp53_ = rui_config_file_reader_check_required_members (self, "UI", _tmp51_, _tmp52_, _tmp52__length1);
				if (!_tmp53_) {
					__vala_JsonObject_free0 (ui_node);
					continue;
				}
				_tmp54_ = ui_node;
				_tmp55_ = json_object_get_string_member (_tmp54_, "id");
				_tmp56_ = g_strdup (_tmp55_);
				_tmp57_ = ui_node;
				_tmp58_ = json_object_get_string_member (_tmp57_, "name");
				_tmp59_ = g_strdup (_tmp58_);
				memset (&_tmp60_, 0, sizeof (RUIRemoteUI));
				_g_free0 (_tmp60_.id);
				_tmp60_.id = _tmp56_;
				_g_free0 (_tmp60_.name);
				_tmp60_.name = _tmp59_;
				remoteUI = _tmp60_;
				_tmp61_ = remoteUIs;
				_tmp62_ = remoteUI;
				_tmp63_ = _tmp62_.id;
				_tmp64_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp61_, _tmp63_);
				if (_tmp64_) {
					FILE* _tmp65_;
					RUIRemoteUI _tmp66_;
					const gchar* _tmp67_;
					_tmp65_ = stderr;
					_tmp66_ = remoteUI;
					_tmp67_ = _tmp66_.id;
					fprintf (_tmp65_, "Ignoring duplicate RemoteUI id: %s\n", _tmp67_);
					rui_remote_ui_destroy (&remoteUI);
					__vala_JsonObject_free0 (ui_node);
					continue;
				}
				_tmp68_ = ui_node;
				_tmp69_ = json_object_has_member (_tmp68_, "description");
				if (_tmp69_) {
					JsonObject* _tmp70_;
					const gchar* _tmp71_ = NULL;
					gchar* _tmp72_;
					_tmp70_ = ui_node;
					_tmp71_ = json_object_get_string_member (_tmp70_, "description");
					_tmp72_ = g_strdup (_tmp71_);
					_g_free0 (remoteUI.description);
					remoteUI.description = _tmp72_;
				}
				_tmp73_ = g_new0 (RUIProtocol, 0);
				protocols = _tmp73_;
				protocols_length1 = 0;
				_protocols_size_ = protocols_length1;
				_tmp74_ = ui_node;
				_tmp75_ = json_object_get_array_member (_tmp74_, "protocols");
				_tmp76_ = __vala_JsonArray_copy0 (_tmp75_);
				protocols_node = _tmp76_;
				{
					gint j;
					j = 0;
					{
						gboolean _tmp77_;
						_tmp77_ = TRUE;
						while (TRUE) {
							gboolean _tmp78_;
							gint _tmp80_;
							JsonArray* _tmp81_;
							guint _tmp82_ = 0U;
							JsonArray* _tmp83_;
							gint _tmp84_;
							JsonNode* _tmp85_ = NULL;
							JsonObject* _tmp86_ = NULL;
							JsonObject* _tmp87_;
							JsonObject* protocol_node;
							gchar* _tmp88_;
							gchar* _tmp89_;
							gchar** _tmp90_ = NULL;
							JsonObject* _tmp91_;
							gchar** _tmp92_;
							gint _tmp92__length1;
							gboolean _tmp93_ = FALSE;
							JsonObject* _tmp94_;
							const gchar* _tmp95_ = NULL;
							gchar* _tmp96_;
							RUIProtocol _tmp97_ = {0};
							RUIProtocol protocol;
							gchar** _tmp98_ = NULL;
							gchar** urls;
							gint urls_length1;
							gint _urls_size_;
							JsonObject* _tmp99_;
							JsonArray* _tmp100_ = NULL;
							JsonArray* _tmp101_;
							JsonArray* urls_node;
							gchar** _tmp114_;
							gint _tmp114__length1;
							gchar** _tmp116_;
							gint _tmp116__length1;
							gchar** _tmp117_;
							gint _tmp117__length1;
							RUIProtocol* _tmp118_;
							gint _tmp118__length1;
							RUIProtocol _tmp119_;
							RUIProtocol _tmp120_ = {0};
							_tmp78_ = _tmp77_;
							if (!_tmp78_) {
								gint _tmp79_;
								_tmp79_ = j;
								j = _tmp79_ + 1;
							}
							_tmp77_ = FALSE;
							_tmp80_ = j;
							_tmp81_ = protocols_node;
							_tmp82_ = json_array_get_length (_tmp81_);
							if (!(((guint) _tmp80_) < _tmp82_)) {
								break;
							}
							_tmp83_ = protocols_node;
							_tmp84_ = j;
							_tmp85_ = json_array_get_element (_tmp83_, (guint) _tmp84_);
							_tmp86_ = json_node_get_object (_tmp85_);
							_tmp87_ = __vala_JsonObject_copy0 (_tmp86_);
							protocol_node = _tmp87_;
							_tmp88_ = g_strdup ("urls");
							_tmp89_ = g_strdup ("shortName");
							_tmp90_ = g_new0 (gchar*, 2 + 1);
							_tmp90_[0] = _tmp88_;
							_tmp90_[1] = _tmp89_;
							required_members = (_vala_array_free (required_members, required_members_length1, (GDestroyNotify) g_free), NULL);
							required_members = _tmp90_;
							required_members_length1 = 2;
							_required_members_size_ = required_members_length1;
							_tmp91_ = protocol_node;
							_tmp92_ = required_members;
							_tmp92__length1 = required_members_length1;
							_tmp93_ = rui_config_file_reader_check_required_members (self, "protocol", _tmp91_, _tmp92_, _tmp92__length1);
							if (!_tmp93_) {
								__vala_JsonObject_free0 (protocol_node);
								continue;
							}
							_tmp94_ = protocol_node;
							_tmp95_ = json_object_get_string_member (_tmp94_, "shortName");
							_tmp96_ = g_strdup (_tmp95_);
							memset (&_tmp97_, 0, sizeof (RUIProtocol));
							_g_free0 (_tmp97_.shortName);
							_tmp97_.shortName = _tmp96_;
							protocol = _tmp97_;
							_tmp98_ = g_new0 (gchar*, 0 + 1);
							urls = _tmp98_;
							urls_length1 = 0;
							_urls_size_ = urls_length1;
							_tmp99_ = protocol_node;
							_tmp100_ = json_object_get_array_member (_tmp99_, "urls");
							_tmp101_ = __vala_JsonArray_copy0 (_tmp100_);
							urls_node = _tmp101_;
							{
								gint k;
								k = 0;
								{
									gboolean _tmp102_;
									_tmp102_ = TRUE;
									while (TRUE) {
										gboolean _tmp103_;
										gint _tmp105_;
										JsonArray* _tmp106_;
										guint _tmp107_ = 0U;
										gchar** _tmp108_;
										gint _tmp108__length1;
										JsonArray* _tmp109_;
										gint _tmp110_;
										JsonNode* _tmp111_ = NULL;
										const gchar* _tmp112_ = NULL;
										gchar* _tmp113_;
										_tmp103_ = _tmp102_;
										if (!_tmp103_) {
											gint _tmp104_;
											_tmp104_ = k;
											k = _tmp104_ + 1;
										}
										_tmp102_ = FALSE;
										_tmp105_ = k;
										_tmp106_ = urls_node;
										_tmp107_ = json_array_get_length (_tmp106_);
										if (!(((guint) _tmp105_) < _tmp107_)) {
											break;
										}
										_tmp108_ = urls;
										_tmp108__length1 = urls_length1;
										_tmp109_ = urls_node;
										_tmp110_ = k;
										_tmp111_ = json_array_get_element (_tmp109_, (guint) _tmp110_);
										_tmp112_ = json_node_get_string (_tmp111_);
										_tmp113_ = g_strdup (_tmp112_);
										_vala_array_add1 (&urls, &urls_length1, &_urls_size_, _tmp113_);
									}
								}
							}
							_tmp114_ = urls;
							_tmp114__length1 = urls_length1;
							if (_tmp114__length1 == 0) {
								FILE* _tmp115_;
								_tmp115_ = stderr;
								fprintf (_tmp115_, "Ignoring invalid protocols attribute with no urls.\n");
								__vala_JsonArray_free0 (urls_node);
								urls = (_vala_array_free (urls, urls_length1, (GDestroyNotify) g_free), NULL);
								rui_protocol_destroy (&protocol);
								__vala_JsonObject_free0 (protocol_node);
								continue;
							}
							_tmp116_ = urls;
							_tmp116__length1 = urls_length1;
							_tmp117_ = (_tmp116_ != NULL) ? _vala_array_dup1 (_tmp116_, _tmp116__length1) : ((gpointer) _tmp116_);
							_tmp117__length1 = _tmp116__length1;
							protocol.urls = (_vala_array_free (protocol.urls, protocol.urls_length1, (GDestroyNotify) g_free), NULL);
							protocol.urls = _tmp117_;
							protocol.urls_length1 = _tmp117__length1;
							_tmp118_ = protocols;
							_tmp118__length1 = protocols_length1;
							_tmp119_ = protocol;
							rui_protocol_copy (&_tmp119_, &_tmp120_);
							_vala_array_add2 (&protocols, &protocols_length1, &_protocols_size_, &_tmp120_);
							__vala_JsonArray_free0 (urls_node);
							urls = (_vala_array_free (urls, urls_length1, (GDestroyNotify) g_free), NULL);
							rui_protocol_destroy (&protocol);
							__vala_JsonObject_free0 (protocol_node);
						}
					}
				}
				_tmp121_ = protocols;
				_tmp121__length1 = protocols_length1;
				if (_tmp121__length1 == 0) {
					FILE* _tmp122_;
					_tmp122_ = stderr;
					fprintf (_tmp122_, "Ignoring invalid RemoteUI with 0-length protocol list.\n");
					__vala_JsonArray_free0 (protocols_node);
					protocols = (_vala_RUIProtocol_array_free (protocols, protocols_length1), NULL);
					rui_remote_ui_destroy (&remoteUI);
					__vala_JsonObject_free0 (ui_node);
					continue;
				}
				_tmp123_ = protocols;
				_tmp123__length1 = protocols_length1;
				_tmp124_ = (_tmp123_ != NULL) ? _vala_array_dup2 (_tmp123_, _tmp123__length1) : ((gpointer) _tmp123_);
				_tmp124__length1 = _tmp123__length1;
				remoteUI.protocols = (_vala_RUIProtocol_array_free (remoteUI.protocols, remoteUI.protocols_length1), NULL);
				remoteUI.protocols = _tmp124_;
				remoteUI.protocols_length1 = _tmp124__length1;
				_tmp125_ = ui_node;
				_tmp126_ = json_object_has_member (_tmp125_, "icons");
				if (_tmp126_) {
					RUIIcon* _tmp127_ = NULL;
					RUIIcon* icons;
					gint icons_length1;
					gint _icons_size_;
					JsonObject* _tmp128_;
					JsonArray* _tmp129_ = NULL;
					JsonArray* _tmp130_;
					JsonArray* icons_node;
					RUIIcon* _tmp178_;
					gint _tmp178__length1;
					_tmp127_ = g_new0 (RUIIcon, 0);
					icons = _tmp127_;
					icons_length1 = 0;
					_icons_size_ = icons_length1;
					_tmp128_ = ui_node;
					_tmp129_ = json_object_get_array_member (_tmp128_, "icons");
					_tmp130_ = __vala_JsonArray_copy0 (_tmp129_);
					icons_node = _tmp130_;
					{
						gint j;
						j = 0;
						{
							gboolean _tmp131_;
							_tmp131_ = TRUE;
							while (TRUE) {
								gboolean _tmp132_;
								gint _tmp134_;
								JsonArray* _tmp135_;
								guint _tmp136_ = 0U;
								JsonArray* _tmp137_;
								gint _tmp138_;
								JsonNode* _tmp139_ = NULL;
								JsonObject* _tmp140_ = NULL;
								JsonObject* _tmp141_;
								JsonObject* icon_node;
								gchar* _tmp142_;
								gchar** _tmp143_ = NULL;
								JsonObject* _tmp144_;
								gchar** _tmp145_;
								gint _tmp145__length1;
								gboolean _tmp146_ = FALSE;
								JsonObject* _tmp147_;
								const gchar* _tmp148_ = NULL;
								gchar* _tmp149_;
								RUIIcon _tmp150_ = {0};
								RUIIcon icon;
								JsonObject* _tmp151_;
								gboolean _tmp152_ = FALSE;
								JsonObject* _tmp163_;
								gboolean _tmp164_ = FALSE;
								RUIIcon* _tmp175_;
								gint _tmp175__length1;
								RUIIcon _tmp176_;
								RUIIcon _tmp177_ = {0};
								_tmp132_ = _tmp131_;
								if (!_tmp132_) {
									gint _tmp133_;
									_tmp133_ = j;
									j = _tmp133_ + 1;
								}
								_tmp131_ = FALSE;
								_tmp134_ = j;
								_tmp135_ = icons_node;
								_tmp136_ = json_array_get_length (_tmp135_);
								if (!(((guint) _tmp134_) < _tmp136_)) {
									break;
								}
								_tmp137_ = icons_node;
								_tmp138_ = j;
								_tmp139_ = json_array_get_element (_tmp137_, (guint) _tmp138_);
								_tmp140_ = json_node_get_object (_tmp139_);
								_tmp141_ = __vala_JsonObject_copy0 (_tmp140_);
								icon_node = _tmp141_;
								_tmp142_ = g_strdup ("url");
								_tmp143_ = g_new0 (gchar*, 1 + 1);
								_tmp143_[0] = _tmp142_;
								required_members = (_vala_array_free (required_members, required_members_length1, (GDestroyNotify) g_free), NULL);
								required_members = _tmp143_;
								required_members_length1 = 1;
								_required_members_size_ = required_members_length1;
								_tmp144_ = icon_node;
								_tmp145_ = required_members;
								_tmp145__length1 = required_members_length1;
								_tmp146_ = rui_config_file_reader_check_required_members (self, "icon", _tmp144_, _tmp145_, _tmp145__length1);
								if (!_tmp146_) {
									__vala_JsonObject_free0 (icon_node);
									continue;
								}
								_tmp147_ = icon_node;
								_tmp148_ = json_object_get_string_member (_tmp147_, "url");
								_tmp149_ = g_strdup (_tmp148_);
								memset (&_tmp150_, 0, sizeof (RUIIcon));
								_g_free0 (_tmp150_.url);
								_tmp150_.url = _tmp149_;
								icon = _tmp150_;
								_tmp151_ = icon_node;
								_tmp152_ = json_object_has_member (_tmp151_, "width");
								if (_tmp152_) {
									JsonObject* _tmp153_;
									gint64 _tmp154_ = 0LL;
									gint64 width;
									gint64 _tmp155_;
									_tmp153_ = icon_node;
									_tmp154_ = json_object_get_int_member (_tmp153_, "width");
									width = _tmp154_;
									_tmp155_ = width;
									if (_tmp155_ > ((gint64) 0)) {
										gint64 _tmp156_;
										guint64 _tmp157_;
										guint64* _tmp158_;
										_tmp156_ = width;
										_tmp157_ = (guint64) _tmp156_;
										_tmp158_ = __uint64_dup0 (&_tmp157_);
										_g_free0 (icon.width);
										icon.width = _tmp158_;
									} else {
										FILE* _tmp159_;
										gint64 _tmp160_;
										RUIIcon _tmp161_;
										const gchar* _tmp162_;
										_tmp159_ = stderr;
										_tmp160_ = width;
										_tmp161_ = icon;
										_tmp162_ = _tmp161_.url;
										fprintf (_tmp159_, "Ignoring invalid width %" G_GINT64_FORMAT " for URL %s.\n", _tmp160_, _tmp162_);
									}
								}
								_tmp163_ = icon_node;
								_tmp164_ = json_object_has_member (_tmp163_, "height");
								if (_tmp164_) {
									JsonObject* _tmp165_;
									gint64 _tmp166_ = 0LL;
									gint64 height;
									gint64 _tmp167_;
									_tmp165_ = icon_node;
									_tmp166_ = json_object_get_int_member (_tmp165_, "height");
									height = _tmp166_;
									_tmp167_ = height;
									if (_tmp167_ > ((gint64) 0)) {
										gint64 _tmp168_;
										guint64 _tmp169_;
										guint64* _tmp170_;
										_tmp168_ = height;
										_tmp169_ = (guint64) _tmp168_;
										_tmp170_ = __uint64_dup0 (&_tmp169_);
										_g_free0 (icon.height);
										icon.height = _tmp170_;
									} else {
										FILE* _tmp171_;
										gint64 _tmp172_;
										RUIIcon _tmp173_;
										const gchar* _tmp174_;
										_tmp171_ = stderr;
										_tmp172_ = height;
										_tmp173_ = icon;
										_tmp174_ = _tmp173_.url;
										fprintf (_tmp171_, "Ignoring invalid height %" G_GINT64_FORMAT " for URL %s.\n", _tmp172_, _tmp174_);
									}
								}
								_tmp175_ = icons;
								_tmp175__length1 = icons_length1;
								_tmp176_ = icon;
								rui_icon_copy (&_tmp176_, &_tmp177_);
								_vala_array_add3 (&icons, &icons_length1, &_icons_size_, &_tmp177_);
								rui_icon_destroy (&icon);
								__vala_JsonObject_free0 (icon_node);
							}
						}
					}
					_tmp178_ = icons;
					_tmp178__length1 = icons_length1;
					if (_tmp178__length1 == 0) {
						FILE* _tmp179_;
						RUIRemoteUI _tmp180_;
						const gchar* _tmp181_;
						_tmp179_ = stderr;
						_tmp180_ = remoteUI;
						_tmp181_ = _tmp180_.name;
						fprintf (_tmp179_, "Ignoring invalid 0-length icons list for UI %s.\n", _tmp181_);
						remoteUI.icons = (_vala_RUIIcon_array_free (remoteUI.icons, remoteUI.icons_length1), NULL);
						remoteUI.icons = NULL;
						remoteUI.icons_length1 = 0;
					} else {
						RUIIcon* _tmp182_;
						gint _tmp182__length1;
						RUIIcon* _tmp183_;
						gint _tmp183__length1;
						_tmp182_ = icons;
						_tmp182__length1 = icons_length1;
						_tmp183_ = (_tmp182_ != NULL) ? _vala_array_dup3 (_tmp182_, _tmp182__length1) : ((gpointer) _tmp182_);
						_tmp183__length1 = _tmp182__length1;
						remoteUI.icons = (_vala_RUIIcon_array_free (remoteUI.icons, remoteUI.icons_length1), NULL);
						remoteUI.icons = _tmp183_;
						remoteUI.icons_length1 = _tmp183__length1;
					}
					__vala_JsonArray_free0 (icons_node);
					icons = (_vala_RUIIcon_array_free (icons, icons_length1), NULL);
				}
				_tmp184_ = remoteUIs;
				_tmp185_ = remoteUI;
				_tmp186_ = _tmp185_.id;
				_tmp187_ = remoteUI;
				gee_abstract_map_set ((GeeAbstractMap*) _tmp184_, _tmp186_, &_tmp187_);
				__vala_JsonArray_free0 (protocols_node);
				protocols = (_vala_RUIProtocol_array_free (protocols, protocols_length1), NULL);
				rui_remote_ui_destroy (&remoteUI);
				__vala_JsonObject_free0 (ui_node);
			}
		}
	}
	_tmp188_ = g_new0 (gchar*, 0 + 1);
	changed_uis = _tmp188_;
	changed_uis_length1 = 0;
	_changed_uis_size_ = changed_uis_length1;
	{
		GeeCollection* _tmp189_;
		GeeCollection* _tmp190_;
		GeeCollection* _tmp191_;
		GeeIterator* _tmp192_ = NULL;
		GeeIterator* _tmp193_;
		GeeIterator* _ui_it;
		_tmp189_ = rui_config_file_reader_get_remoteUIs (self);
		_tmp190_ = _tmp189_;
		_tmp191_ = _tmp190_;
		_tmp192_ = gee_iterable_iterator ((GeeIterable*) _tmp191_);
		_tmp193_ = _tmp192_;
		_g_object_unref0 (_tmp191_);
		_ui_it = _tmp193_;
		while (TRUE) {
			GeeIterator* _tmp194_;
			gboolean _tmp195_ = FALSE;
			GeeIterator* _tmp196_;
			gpointer _tmp197_ = NULL;
			RUIRemoteUI* ui;
			GeeHashMap* _tmp198_;
			RUIRemoteUI* _tmp199_;
			const gchar* _tmp200_;
			RUIRemoteUI* _tmp201_;
			gboolean _tmp202_ = FALSE;
			_tmp194_ = _ui_it;
			_tmp195_ = gee_iterator_next (_tmp194_);
			if (!_tmp195_) {
				break;
			}
			_tmp196_ = _ui_it;
			_tmp197_ = gee_iterator_get (_tmp196_);
			ui = (RUIRemoteUI*) _tmp197_;
			_tmp198_ = remoteUIs;
			_tmp199_ = ui;
			_tmp200_ = (*_tmp199_).id;
			_tmp201_ = ui;
			_tmp202_ = gee_abstract_map_has ((GeeAbstractMap*) _tmp198_, _tmp200_, _tmp201_);
			if (!_tmp202_) {
				gchar** _tmp203_;
				gint _tmp203__length1;
				RUIRemoteUI* _tmp204_;
				const gchar* _tmp205_;
				gchar* _tmp206_;
				_tmp203_ = changed_uis;
				_tmp203__length1 = changed_uis_length1;
				_tmp204_ = ui;
				_tmp205_ = (*_tmp204_).id;
				_tmp206_ = g_strdup (_tmp205_);
				_vala_array_add4 (&changed_uis, &changed_uis_length1, &_changed_uis_size_, _tmp206_);
			}
			_rui_remote_ui_free0 (ui);
		}
		_g_object_unref0 (_ui_it);
	}
	{
		GeeHashMap* _tmp207_;
		GeeSet* _tmp208_;
		GeeSet* _tmp209_;
		GeeSet* _tmp210_;
		GeeIterator* _tmp211_ = NULL;
		GeeIterator* _tmp212_;
		GeeIterator* _id_it;
		_tmp207_ = remoteUIs;
		_tmp208_ = gee_abstract_map_get_keys ((GeeMap*) _tmp207_);
		_tmp209_ = _tmp208_;
		_tmp210_ = _tmp209_;
		_tmp211_ = gee_iterable_iterator ((GeeIterable*) _tmp210_);
		_tmp212_ = _tmp211_;
		_g_object_unref0 (_tmp210_);
		_id_it = _tmp212_;
		while (TRUE) {
			GeeIterator* _tmp213_;
			gboolean _tmp214_ = FALSE;
			GeeIterator* _tmp215_;
			gpointer _tmp216_ = NULL;
			gchar* id;
			GeeMap* _tmp217_;
			const gchar* _tmp218_;
			gboolean _tmp219_ = FALSE;
			_tmp213_ = _id_it;
			_tmp214_ = gee_iterator_next (_tmp213_);
			if (!_tmp214_) {
				break;
			}
			_tmp215_ = _id_it;
			_tmp216_ = gee_iterator_get (_tmp215_);
			id = (gchar*) _tmp216_;
			_tmp217_ = self->priv->_remoteUIs;
			_tmp218_ = id;
			_tmp219_ = gee_map_has_key (_tmp217_, _tmp218_);
			if (!_tmp219_) {
				gchar** _tmp220_;
				gint _tmp220__length1;
				const gchar* _tmp221_;
				gchar* _tmp222_;
				_tmp220_ = changed_uis;
				_tmp220__length1 = changed_uis_length1;
				_tmp221_ = id;
				_tmp222_ = g_strdup (_tmp221_);
				_vala_array_add5 (&changed_uis, &changed_uis_length1, &_changed_uis_size_, _tmp222_);
			}
			_g_free0 (id);
		}
		_g_object_unref0 (_id_it);
	}
	_tmp223_ = remoteUIs;
	_tmp224_ = _g_object_ref0 ((GeeMap*) _tmp223_);
	_g_object_unref0 (self->priv->_remoteUIs);
	self->priv->_remoteUIs = _tmp224_;
	_tmp225_ = changed_uis;
	_tmp225__length1 = changed_uis_length1;
	g_signal_emit_by_name (self, "remote-uis-changed", _tmp225_, _tmp225__length1);
	changed_uis = (_vala_array_free (changed_uis, changed_uis_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (remoteUIs);
	__vala_JsonArray_free0 (uis);
	required_members = (_vala_array_free (required_members, required_members_length1, (GDestroyNotify) g_free), NULL);
	__vala_JsonObject_free0 (object);
	__vala_JsonNode_free0 (root);
	_g_object_unref0 (parser);
}


static void _rui_config_file_reader_on_config_file_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	rui_config_file_reader_on_config_file_changed (self, file, other_file, event_type);
}


void rui_config_file_reader_watch_config_file (RUIConfigFileReader* self, GError** error) {
	GFileMonitor* _tmp0_;
	const gchar* _tmp2_;
	GFile* _tmp3_ = NULL;
	GFile* file;
	FILE* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	GFileMonitor* _tmp7_ = NULL;
	GFileMonitor* _tmp8_;
	GFileMonitor* _tmp9_;
	GFileMonitor* _tmp10_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->file_monitor;
	if (_tmp0_ != NULL) {
		GFileMonitor* _tmp1_;
		_tmp1_ = self->priv->file_monitor;
		g_file_monitor_cancel (_tmp1_);
	}
	_tmp2_ = self->priv->config_file;
	_tmp3_ = g_file_new_for_path (_tmp2_);
	file = _tmp3_;
	_tmp4_ = stdout;
	_tmp5_ = g_file_get_path (file);
	_tmp6_ = _tmp5_;
	fprintf (_tmp4_, "Watching %s\n", _tmp6_);
	_g_free0 (_tmp6_);
	_tmp7_ = g_file_monitor (file, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
	_tmp8_ = _tmp7_;
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (file);
		return;
	}
	_tmp9_ = _g_object_ref0 (_tmp8_);
	_g_object_unref0 (self->priv->file_monitor);
	self->priv->file_monitor = _tmp9_;
	_tmp10_ = self->priv->file_monitor;
	g_signal_connect (_tmp10_, "changed", (GCallback) _rui_config_file_reader_on_config_file_changed_g_file_monitor_changed, self);
	_g_object_unref0 (file);
}


static void rui_config_file_reader_on_config_file_changed (RUIConfigFileReader* self, GFile* file, GFile* other_file, GFileMonitorEvent event) {
	gboolean _tmp0_ = FALSE;
	GFileMonitorEvent _tmp1_;
	gboolean _tmp3_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (file != NULL);
	_tmp1_ = event;
	if (_tmp1_ != G_FILE_MONITOR_EVENT_CHANGED) {
		GFileMonitorEvent _tmp2_;
		_tmp2_ = event;
		_tmp0_ = _tmp2_ != G_FILE_MONITOR_EVENT_CREATED;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		return;
	}
	{
		rui_config_file_reader_parse_config_file (self, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stderr;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "Error parsing changed config file: %s. Continuing to use the old confi" \
"g file.\n", _tmp6_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


const gchar* rui_config_file_reader_get_root_device_xml (RUIConfigFileReader* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_root_device_xml;
	result = _tmp0_;
	return result;
}


static void rui_config_file_reader_set_root_device_xml (RUIConfigFileReader* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_root_device_xml);
	self->priv->_root_device_xml = _tmp1_;
}


const gchar* rui_config_file_reader_get_service_directory (RUIConfigFileReader* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_service_directory;
	result = _tmp0_;
	return result;
}


static void rui_config_file_reader_set_service_directory (RUIConfigFileReader* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_service_directory);
	self->priv->_service_directory = _tmp1_;
}


GeeCollection* rui_config_file_reader_get_remoteUIs (RUIConfigFileReader* self) {
	GeeCollection* result;
	GeeMap* _tmp0_;
	GeeCollection* _tmp1_;
	GeeCollection* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_remoteUIs;
	_tmp1_ = gee_map_get_values (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


static void g_cclosure_user_marshal_VOID__BOXED_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__BOXED_INT) (gpointer data1, gpointer arg_1, gint arg_2, gpointer data2);
	register GMarshalFunc_VOID__BOXED_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__BOXED_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_boxed (param_values + 1), g_value_get_int (param_values + 2), data2);
}


static void rui_value_config_file_reader_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void rui_value_config_file_reader_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		rui_config_file_reader_unref (value->data[0].v_pointer);
	}
}


static void rui_value_config_file_reader_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = rui_config_file_reader_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer rui_value_config_file_reader_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* rui_value_config_file_reader_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		RUIConfigFileReader* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = rui_config_file_reader_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* rui_value_config_file_reader_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	RUIConfigFileReader** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = rui_config_file_reader_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* rui_param_spec_config_file_reader (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	RUIParamSpecConfigFileReader* spec;
	g_return_val_if_fail (g_type_is_a (object_type, RUI_TYPE_CONFIG_FILE_READER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer rui_value_get_config_file_reader (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_CONFIG_FILE_READER), NULL);
	return value->data[0].v_pointer;
}


void rui_value_set_config_file_reader (GValue* value, gpointer v_object) {
	RUIConfigFileReader* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_CONFIG_FILE_READER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, RUI_TYPE_CONFIG_FILE_READER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		rui_config_file_reader_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		rui_config_file_reader_unref (old);
	}
}


void rui_value_take_config_file_reader (GValue* value, gpointer v_object) {
	RUIConfigFileReader* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_CONFIG_FILE_READER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, RUI_TYPE_CONFIG_FILE_READER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		rui_config_file_reader_unref (old);
	}
}


static void rui_config_file_reader_class_init (RUIConfigFileReaderClass * klass) {
	rui_config_file_reader_parent_class = g_type_class_peek_parent (klass);
	RUI_CONFIG_FILE_READER_CLASS (klass)->finalize = rui_config_file_reader_finalize;
	g_type_class_add_private (klass, sizeof (RUIConfigFileReaderPrivate));
	g_signal_new ("remote_uis_changed", RUI_TYPE_CONFIG_FILE_READER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
}


static void rui_config_file_reader_instance_init (RUIConfigFileReader * self) {
	GeeHashMap* _tmp0_;
	self->priv = RUI_CONFIG_FILE_READER_GET_PRIVATE (self);
	self->priv->file_monitor = NULL;
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, RUI_TYPE_REMOTE_UI, (GBoxedCopyFunc) rui_remote_ui_dup, rui_remote_ui_free, NULL, NULL, NULL);
	self->priv->_remoteUIs = (GeeMap*) _tmp0_;
	self->ref_count = 1;
}


static void rui_config_file_reader_finalize (RUIConfigFileReader* obj) {
	RUIConfigFileReader * self;
	self = RUI_CONFIG_FILE_READER (obj);
	_g_free0 (self->priv->_root_device_xml);
	_g_free0 (self->priv->_service_directory);
	_g_free0 (self->priv->config_file);
	_g_object_unref0 (self->priv->file_monitor);
	_g_object_unref0 (self->priv->_remoteUIs);
}


GType rui_config_file_reader_get_type (void) {
	static volatile gsize rui_config_file_reader_type_id__volatile = 0;
	if (g_once_init_enter (&rui_config_file_reader_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { rui_value_config_file_reader_init, rui_value_config_file_reader_free_value, rui_value_config_file_reader_copy_value, rui_value_config_file_reader_peek_pointer, "p", rui_value_config_file_reader_collect_value, "p", rui_value_config_file_reader_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (RUIConfigFileReaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rui_config_file_reader_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RUIConfigFileReader), 0, (GInstanceInitFunc) rui_config_file_reader_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType rui_config_file_reader_type_id;
		rui_config_file_reader_type_id = g_type_register_fundamental (g_type_fundamental_next (), "RUIConfigFileReader", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&rui_config_file_reader_type_id__volatile, rui_config_file_reader_type_id);
	}
	return rui_config_file_reader_type_id__volatile;
}


gpointer rui_config_file_reader_ref (gpointer instance) {
	RUIConfigFileReader* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void rui_config_file_reader_unref (gpointer instance) {
	RUIConfigFileReader* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		RUI_CONFIG_FILE_READER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



