/* main.c generated by valac 0.14.2, the Vala compiler
 * generated from main.vala, do not modify */

/* Copyright (c) 2014, CableLabs, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <signal.h>

#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define RUI_TYPE_CONFIG_FILE_READER (rui_config_file_reader_get_type ())
#define RUI_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReader))
#define RUI_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))
#define RUI_IS_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_IS_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_CONFIG_FILE_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))

typedef struct _RUIConfigFileReader RUIConfigFileReader;
typedef struct _RUIConfigFileReaderClass RUIConfigFileReaderClass;
#define _rui_config_file_reader_unref0(var) ((var == NULL) ? NULL : (var = (rui_config_file_reader_unref (var), NULL)))

#define RUI_TYPE_REMOTE_UI_SERVER (rui_remote_ui_server_get_type ())
#define RUI_REMOTE_UI_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServer))
#define RUI_REMOTE_UI_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServerClass))
#define RUI_IS_REMOTE_UI_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUI_TYPE_REMOTE_UI_SERVER))
#define RUI_IS_REMOTE_UI_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUI_TYPE_REMOTE_UI_SERVER))
#define RUI_REMOTE_UI_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServerClass))

typedef struct _RUIRemoteUIServer RUIRemoteUIServer;
typedef struct _RUIRemoteUIServerClass RUIRemoteUIServerClass;
#define _rui_remote_ui_server_unref0(var) ((var == NULL) ? NULL : (var = (rui_remote_ui_server_unref (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))


extern gchar* config_file;
gchar* config_file = NULL;
extern gchar* iface;
gchar* iface = NULL;
extern gboolean debug;
gboolean debug = FALSE;
extern gboolean watch;
gboolean watch = FALSE;
extern GMainLoop* loop;
GMainLoop* loop = NULL;

void safe_exit (gint signal);
gint _vala_main (gchar** args, int args_length1);
gpointer rui_config_file_reader_ref (gpointer instance);
void rui_config_file_reader_unref (gpointer instance);
GParamSpec* rui_param_spec_config_file_reader (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rui_value_set_config_file_reader (GValue* value, gpointer v_object);
void rui_value_take_config_file_reader (GValue* value, gpointer v_object);
gpointer rui_value_get_config_file_reader (const GValue* value);
GType rui_config_file_reader_get_type (void) G_GNUC_CONST;
RUIConfigFileReader* rui_config_file_reader_new (const gchar* config_file);
RUIConfigFileReader* rui_config_file_reader_construct (GType object_type, const gchar* config_file);
void rui_config_file_reader_parse_config_file (RUIConfigFileReader* self, GError** error);
void rui_config_file_reader_watch_config_file (RUIConfigFileReader* self, GError** error);
RUIRemoteUIServer* rui_remote_ui_server_new (RUIConfigFileReader* config);
RUIRemoteUIServer* rui_remote_ui_server_construct (GType object_type, RUIConfigFileReader* config);
gpointer rui_remote_ui_server_ref (gpointer instance);
void rui_remote_ui_server_unref (gpointer instance);
GParamSpec* rui_param_spec_remote_ui_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rui_value_set_remote_ui_server (GValue* value, gpointer v_object);
void rui_value_take_remote_ui_server (GValue* value, gpointer v_object);
gpointer rui_value_get_remote_ui_server (const GValue* value);
GType rui_remote_ui_server_get_type (void) G_GNUC_CONST;
void rui_remote_ui_server_start (RUIRemoteUIServer* self, const gchar* iface, GError** error);
static void _safe_exit_sighandler_t (gint signal);

const GOptionEntry options[5] = {{"config-file", 'c', 0, G_OPTION_ARG_FILENAME, &config_file, "The server config file. See config/config.json for an example.", "[file]"}, {"iface", 'i', 0, G_OPTION_ARG_STRING, &iface, "Network interface for RUI service", NULL}, {"debug", 'd', 0, G_OPTION_ARG_NONE, &debug, "Print debug messages to the console", NULL}, {"watch", 'w', 0, G_OPTION_ARG_NONE, &watch, "Watch the config file and send UIListingUpdate events", NULL}, {NULL}};

void safe_exit (gint signal) {
	GMainLoop* _tmp0_;
	_tmp0_ = loop;
	g_main_loop_quit (_tmp0_);
}


static void _safe_exit_sighandler_t (gint signal) {
	safe_exit (signal);
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	RUIConfigFileReader* config = NULL;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* _tmp0_;
		GOptionContext* opt_context;
		GOptionContext* _tmp1_;
		GOptionContext* _tmp2_;
		GOptionContext* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp6_;
		FILE* _tmp8_;
		const gchar* _tmp9_;
		_tmp0_ = g_option_context_new ("UPnP RemoteUIServer");
		opt_context = _tmp0_;
		_tmp1_ = opt_context;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = opt_context;
		g_option_context_add_main_entries (_tmp2_, options, NULL);
		_tmp3_ = opt_context;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch1_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp4_ = config_file;
		if (_tmp4_ == NULL) {
			GError* _tmp5_;
			_tmp5_ = g_error_new_literal (G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE, "Missing --config-file");
			_inner_error_ = _tmp5_;
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch1_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp6_ = iface;
		if (_tmp6_ == NULL) {
			GError* _tmp7_;
			_tmp7_ = g_error_new_literal (G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE, "Missing --iface");
			_inner_error_ = _tmp7_;
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch1_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp8_ = stdout;
		_tmp9_ = iface;
		fprintf (_tmp8_, "iface:%s\n", _tmp9_);
		_g_option_context_free0 (opt_context);
	}
	goto __finally1;
	__catch1_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp10_;
		GError* _tmp11_;
		const gchar* _tmp12_;
		FILE* _tmp13_;
		gchar** _tmp14_;
		gint _tmp14__length1;
		const gchar* _tmp15_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp10_ = stderr;
		_tmp11_ = e;
		_tmp12_ = _tmp11_->message;
		fprintf (_tmp10_, "%s\n", _tmp12_);
		_tmp13_ = stderr;
		_tmp14_ = args;
		_tmp14__length1 = args_length1;
		_tmp15_ = _tmp14_[0];
		fprintf (_tmp13_, "Run '%s --help' to see a full list of available command line options.\n", _tmp15_);
		result = 2;
		_g_error_free0 (e);
		return result;
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	{
		const gchar* _tmp16_;
		RUIConfigFileReader* _tmp17_;
		RUIConfigFileReader* _tmp18_;
		gboolean _tmp19_;
		_tmp16_ = config_file;
		_tmp17_ = rui_config_file_reader_new (_tmp16_);
		_rui_config_file_reader_unref0 (config);
		config = _tmp17_;
		_tmp18_ = config;
		rui_config_file_reader_parse_config_file (_tmp18_, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
		_tmp19_ = watch;
		if (_tmp19_) {
			RUIConfigFileReader* _tmp20_;
			_tmp20_ = config;
			rui_config_file_reader_watch_config_file (_tmp20_, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch2_g_error;
			}
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		FILE* _tmp21_;
		const gchar* _tmp22_;
		GError* _tmp23_;
		const gchar* _tmp24_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp21_ = stderr;
		_tmp22_ = config_file;
		_tmp23_ = e;
		_tmp24_ = _tmp23_->message;
		fprintf (_tmp21_, "Error reading config file %s: %s\n", _tmp22_, _tmp24_);
		result = 3;
		_g_error_free0 (e);
		_rui_config_file_reader_unref0 (config);
		return result;
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_rui_config_file_reader_unref0 (config);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	{
		RUIConfigFileReader* _tmp25_;
		RUIRemoteUIServer* _tmp26_;
		RUIRemoteUIServer* server;
		RUIRemoteUIServer* _tmp27_;
		const gchar* _tmp28_;
		GMainLoop* _tmp29_;
		GMainLoop* _tmp30_;
		_tmp25_ = config;
		_tmp26_ = rui_remote_ui_server_new (_tmp25_);
		server = _tmp26_;
		_tmp27_ = server;
		_tmp28_ = iface;
		rui_remote_ui_server_start (_tmp27_, _tmp28_, &_inner_error_);
		if (_inner_error_ != NULL) {
			_rui_remote_ui_server_unref0 (server);
			goto __catch3_g_error;
		}
		_tmp29_ = g_main_loop_new (NULL, FALSE);
		_g_main_loop_unref0 (loop);
		loop = _tmp29_;
		signal (SIGINT, _safe_exit_sighandler_t);
		signal (SIGHUP, _safe_exit_sighandler_t);
		signal (SIGTERM, _safe_exit_sighandler_t);
		_tmp30_ = loop;
		g_main_loop_run (_tmp30_);
		result = 0;
		_rui_remote_ui_server_unref0 (server);
		_rui_config_file_reader_unref0 (config);
		return result;
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		FILE* _tmp31_;
		GError* _tmp32_;
		const gchar* _tmp33_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp31_ = stderr;
		_tmp32_ = e;
		_tmp33_ = _tmp32_->message;
		fprintf (_tmp31_, "Error running RemoteUIServer: %s\n", _tmp33_);
		result = 1;
		_g_error_free0 (e);
		_rui_config_file_reader_unref0 (config);
		return result;
	}
	__finally3:
	_rui_config_file_reader_unref0 (config);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



