/* remote-ui.c generated by valac 0.14.2, the Vala compiler
 * generated from remote-ui.vala, do not modify */

/* Copyright (c) 2014, CableLabs, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define RUI_TYPE_ICON (rui_icon_get_type ())
typedef struct _RUIIcon RUIIcon;
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

#define RUI_TYPE_PROTOCOL (rui_protocol_get_type ())
typedef struct _RUIProtocol RUIProtocol;

#define RUI_TYPE_REMOTE_UI (rui_remote_ui_get_type ())
typedef struct _RUIRemoteUI RUIRemoteUI;

struct _RUIIcon {
	guint64* width;
	guint64* height;
	gchar* url;
};

struct _RUIProtocol {
	gchar** urls;
	gint urls_length1;
	gchar* shortName;
};

struct _RUIRemoteUI {
	gchar* id;
	gchar* name;
	gchar* description;
	RUIProtocol* protocols;
	gint protocols_length1;
	RUIIcon* icons;
	gint icons_length1;
};



GType rui_icon_get_type (void) G_GNUC_CONST;
RUIIcon* rui_icon_dup (const RUIIcon* self);
void rui_icon_free (RUIIcon* self);
void rui_icon_copy (const RUIIcon* self, RUIIcon* dest);
void rui_icon_destroy (RUIIcon* self);
static guint64* _uint64_dup (guint64* self);
GType rui_protocol_get_type (void) G_GNUC_CONST;
RUIProtocol* rui_protocol_dup (const RUIProtocol* self);
void rui_protocol_free (RUIProtocol* self);
void rui_protocol_copy (const RUIProtocol* self, RUIProtocol* dest);
void rui_protocol_destroy (RUIProtocol* self);
static gchar** _vala_array_dup4 (gchar** self, int length);
GType rui_remote_ui_get_type (void) G_GNUC_CONST;
RUIRemoteUI* rui_remote_ui_dup (const RUIRemoteUI* self);
void rui_remote_ui_free (RUIRemoteUI* self);
void rui_remote_ui_copy (const RUIRemoteUI* self, RUIRemoteUI* dest);
void rui_remote_ui_destroy (RUIRemoteUI* self);
static void _vala_RUIProtocol_array_free (RUIProtocol* array, gint array_length);
static void _vala_RUIIcon_array_free (RUIIcon* array, gint array_length);
static RUIProtocol* _vala_array_dup5 (RUIProtocol* self, int length);
static RUIIcon* _vala_array_dup6 (RUIIcon* self, int length);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static guint64* _uint64_dup (guint64* self) {
	guint64* dup;
	dup = g_new0 (guint64, 1);
	memcpy (dup, self, sizeof (guint64));
	return dup;
}


static gpointer __uint64_dup0 (gpointer self) {
	return self ? _uint64_dup (self) : NULL;
}


void rui_icon_copy (const RUIIcon* self, RUIIcon* dest) {
	guint64* _tmp0_;
	guint64* _tmp1_;
	guint64* _tmp2_;
	guint64* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	_tmp0_ = (*self).width;
	_tmp1_ = __uint64_dup0 (_tmp0_);
	_g_free0 ((*dest).width);
	(*dest).width = _tmp1_;
	_tmp2_ = (*self).height;
	_tmp3_ = __uint64_dup0 (_tmp2_);
	_g_free0 ((*dest).height);
	(*dest).height = _tmp3_;
	_tmp4_ = (*self).url;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 ((*dest).url);
	(*dest).url = _tmp5_;
}


void rui_icon_destroy (RUIIcon* self) {
	_g_free0 ((*self).width);
	_g_free0 ((*self).height);
	_g_free0 ((*self).url);
}


RUIIcon* rui_icon_dup (const RUIIcon* self) {
	RUIIcon* dup;
	dup = g_new0 (RUIIcon, 1);
	rui_icon_copy (self, dup);
	return dup;
}


void rui_icon_free (RUIIcon* self) {
	rui_icon_destroy (self);
	g_free (self);
}


GType rui_icon_get_type (void) {
	static volatile gsize rui_icon_type_id__volatile = 0;
	if (g_once_init_enter (&rui_icon_type_id__volatile)) {
		GType rui_icon_type_id;
		rui_icon_type_id = g_boxed_type_register_static ("RUIIcon", (GBoxedCopyFunc) rui_icon_dup, (GBoxedFreeFunc) rui_icon_free);
		g_once_init_leave (&rui_icon_type_id__volatile, rui_icon_type_id);
	}
	return rui_icon_type_id__volatile;
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void rui_protocol_copy (const RUIProtocol* self, RUIProtocol* dest) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	_tmp0_ = (*self).urls;
	_tmp0__length1 = (*self).urls_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup4 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	(*dest).urls = (_vala_array_free ((*dest).urls, (*dest).urls_length1, (GDestroyNotify) g_free), NULL);
	(*dest).urls = _tmp1_;
	(*dest).urls_length1 = _tmp1__length1;
	_tmp2_ = (*self).shortName;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).shortName);
	(*dest).shortName = _tmp3_;
}


void rui_protocol_destroy (RUIProtocol* self) {
	(*self).urls = (_vala_array_free ((*self).urls, (*self).urls_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 ((*self).shortName);
}


RUIProtocol* rui_protocol_dup (const RUIProtocol* self) {
	RUIProtocol* dup;
	dup = g_new0 (RUIProtocol, 1);
	rui_protocol_copy (self, dup);
	return dup;
}


void rui_protocol_free (RUIProtocol* self) {
	rui_protocol_destroy (self);
	g_free (self);
}


GType rui_protocol_get_type (void) {
	static volatile gsize rui_protocol_type_id__volatile = 0;
	if (g_once_init_enter (&rui_protocol_type_id__volatile)) {
		GType rui_protocol_type_id;
		rui_protocol_type_id = g_boxed_type_register_static ("RUIProtocol", (GBoxedCopyFunc) rui_protocol_dup, (GBoxedFreeFunc) rui_protocol_free);
		g_once_init_leave (&rui_protocol_type_id__volatile, rui_protocol_type_id);
	}
	return rui_protocol_type_id__volatile;
}


static void _vala_RUIProtocol_array_free (RUIProtocol* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			rui_protocol_destroy (&array[i]);
		}
	}
	g_free (array);
}


static void _vala_RUIIcon_array_free (RUIIcon* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			rui_icon_destroy (&array[i]);
		}
	}
	g_free (array);
}


static RUIProtocol* _vala_array_dup5 (RUIProtocol* self, int length) {
	RUIProtocol* result;
	int i;
	result = g_new0 (RUIProtocol, length);
	for (i = 0; i < length; i++) {
		RUIProtocol _tmp0_ = {0};
		rui_protocol_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


static RUIIcon* _vala_array_dup6 (RUIIcon* self, int length) {
	RUIIcon* result;
	int i;
	result = g_new0 (RUIIcon, length);
	for (i = 0; i < length; i++) {
		RUIIcon _tmp0_ = {0};
		rui_icon_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


void rui_remote_ui_copy (const RUIRemoteUI* self, RUIRemoteUI* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	RUIProtocol* _tmp6_;
	gint _tmp6__length1;
	RUIProtocol* _tmp7_;
	gint _tmp7__length1;
	RUIIcon* _tmp8_;
	gint _tmp8__length1;
	RUIIcon* _tmp9_;
	gint _tmp9__length1;
	_tmp0_ = (*self).id;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).id);
	(*dest).id = _tmp1_;
	_tmp2_ = (*self).name;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp3_;
	_tmp4_ = (*self).description;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 ((*dest).description);
	(*dest).description = _tmp5_;
	_tmp6_ = (*self).protocols;
	_tmp6__length1 = (*self).protocols_length1;
	_tmp7_ = (_tmp6_ != NULL) ? _vala_array_dup5 (_tmp6_, _tmp6__length1) : ((gpointer) _tmp6_);
	_tmp7__length1 = _tmp6__length1;
	(*dest).protocols = (_vala_RUIProtocol_array_free ((*dest).protocols, (*dest).protocols_length1), NULL);
	(*dest).protocols = _tmp7_;
	(*dest).protocols_length1 = _tmp7__length1;
	_tmp8_ = (*self).icons;
	_tmp8__length1 = (*self).icons_length1;
	_tmp9_ = (_tmp8_ != NULL) ? _vala_array_dup6 (_tmp8_, _tmp8__length1) : ((gpointer) _tmp8_);
	_tmp9__length1 = _tmp8__length1;
	(*dest).icons = (_vala_RUIIcon_array_free ((*dest).icons, (*dest).icons_length1), NULL);
	(*dest).icons = _tmp9_;
	(*dest).icons_length1 = _tmp9__length1;
}


void rui_remote_ui_destroy (RUIRemoteUI* self) {
	_g_free0 ((*self).id);
	_g_free0 ((*self).name);
	_g_free0 ((*self).description);
	(*self).protocols = (_vala_RUIProtocol_array_free ((*self).protocols, (*self).protocols_length1), NULL);
	(*self).icons = (_vala_RUIIcon_array_free ((*self).icons, (*self).icons_length1), NULL);
}


RUIRemoteUI* rui_remote_ui_dup (const RUIRemoteUI* self) {
	RUIRemoteUI* dup;
	dup = g_new0 (RUIRemoteUI, 1);
	rui_remote_ui_copy (self, dup);
	return dup;
}


void rui_remote_ui_free (RUIRemoteUI* self) {
	rui_remote_ui_destroy (self);
	g_free (self);
}


GType rui_remote_ui_get_type (void) {
	static volatile gsize rui_remote_ui_type_id__volatile = 0;
	if (g_once_init_enter (&rui_remote_ui_type_id__volatile)) {
		GType rui_remote_ui_type_id;
		rui_remote_ui_type_id = g_boxed_type_register_static ("RUIRemoteUI", (GBoxedCopyFunc) rui_remote_ui_dup, (GBoxedFreeFunc) rui_remote_ui_free);
		g_once_init_leave (&rui_remote_ui_type_id__volatile, rui_remote_ui_type_id);
	}
	return rui_remote_ui_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



