/* server.c generated by valac 0.14.2, the Vala compiler
 * generated from server.vala, do not modify */

/* Copyright (c) 2014, CableLabs, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libgupnp/gupnp.h>
#include <gee.h>
#include <stdio.h>
#include <libgssdp/gssdp.h>
#include <gobject/gvaluecollector.h>


#define RUI_TYPE_REMOTE_UI_SERVER (rui_remote_ui_server_get_type ())
#define RUI_REMOTE_UI_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServer))
#define RUI_REMOTE_UI_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServerClass))
#define RUI_IS_REMOTE_UI_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUI_TYPE_REMOTE_UI_SERVER))
#define RUI_IS_REMOTE_UI_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUI_TYPE_REMOTE_UI_SERVER))
#define RUI_REMOTE_UI_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServerClass))

typedef struct _RUIRemoteUIServer RUIRemoteUIServer;
typedef struct _RUIRemoteUIServerClass RUIRemoteUIServerClass;
typedef struct _RUIRemoteUIServerPrivate RUIRemoteUIServerPrivate;

#define RUI_TYPE_REMOTE_UI (rui_remote_ui_get_type ())

#define RUI_TYPE_PROTOCOL (rui_protocol_get_type ())
typedef struct _RUIProtocol RUIProtocol;

#define RUI_TYPE_ICON (rui_icon_get_type ())
typedef struct _RUIIcon RUIIcon;
typedef struct _RUIRemoteUI RUIRemoteUI;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define RUI_TYPE_CONFIG_FILE_READER (rui_config_file_reader_get_type ())
#define RUI_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReader))
#define RUI_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))
#define RUI_IS_CONFIG_FILE_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_IS_CONFIG_FILE_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RUI_TYPE_CONFIG_FILE_READER))
#define RUI_CONFIG_FILE_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RUI_TYPE_CONFIG_FILE_READER, RUIConfigFileReaderClass))

typedef struct _RUIConfigFileReader RUIConfigFileReader;
typedef struct _RUIConfigFileReaderClass RUIConfigFileReaderClass;

#define TYPE_XML_BUILDER (xml_builder_get_type ())
#define XML_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XML_BUILDER, XMLBuilder))
#define XML_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XML_BUILDER, XMLBuilderClass))
#define IS_XML_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XML_BUILDER))
#define IS_XML_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XML_BUILDER))
#define XML_BUILDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XML_BUILDER, XMLBuilderClass))

typedef struct _XMLBuilder XMLBuilder;
typedef struct _XMLBuilderClass XMLBuilderClass;
#define _xml_builder_unref0(var) ((var == NULL) ? NULL : (var = (xml_builder_unref (var), NULL)))
#define _rui_remote_ui_free0(var) ((var == NULL) ? NULL : (var = (rui_remote_ui_free (var), NULL)))
typedef struct _RUIParamSpecRemoteUIServer RUIParamSpecRemoteUIServer;

typedef enum  {
	RUI_ERROR_BAD_CONFIG
} RUIError;
#define RUI_ERROR rui_error_quark ()
struct _RUIRemoteUIServer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RUIRemoteUIServerPrivate * priv;
};

struct _RUIRemoteUIServerClass {
	GTypeClass parent_class;
	void (*finalize) (RUIRemoteUIServer *self);
};

struct _RUIProtocol {
	gchar** urls;
	gint urls_length1;
	gchar* shortName;
};

struct _RUIIcon {
	guint64* width;
	guint64* height;
	gchar* url;
};

struct _RUIRemoteUI {
	gchar* id;
	gchar* name;
	gchar* description;
	RUIProtocol* protocols;
	gint protocols_length1;
	RUIIcon* icons;
	gint icons_length1;
};

struct _RUIRemoteUIServerPrivate {
	gchar* root_device_xml;
	gchar* service_directory;
	GUPnPContext* context;
	GUPnPRootDevice* root_device;
	GUPnPService* service;
	GeeCollection* remoteUIs;
};

struct _RUIParamSpecRemoteUIServer {
	GParamSpec parent_instance;
};


static gpointer rui_remote_ui_server_parent_class = NULL;

GQuark rui_error_quark (void);
gpointer rui_remote_ui_server_ref (gpointer instance);
void rui_remote_ui_server_unref (gpointer instance);
GParamSpec* rui_param_spec_remote_ui_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rui_value_set_remote_ui_server (GValue* value, gpointer v_object);
void rui_value_take_remote_ui_server (GValue* value, gpointer v_object);
gpointer rui_value_get_remote_ui_server (const GValue* value);
GType rui_remote_ui_server_get_type (void) G_GNUC_CONST;
GType rui_remote_ui_get_type (void) G_GNUC_CONST;
GType rui_protocol_get_type (void) G_GNUC_CONST;
RUIProtocol* rui_protocol_dup (const RUIProtocol* self);
void rui_protocol_free (RUIProtocol* self);
void rui_protocol_copy (const RUIProtocol* self, RUIProtocol* dest);
void rui_protocol_destroy (RUIProtocol* self);
GType rui_icon_get_type (void) G_GNUC_CONST;
RUIIcon* rui_icon_dup (const RUIIcon* self);
void rui_icon_free (RUIIcon* self);
void rui_icon_copy (const RUIIcon* self, RUIIcon* dest);
void rui_icon_destroy (RUIIcon* self);
RUIRemoteUI* rui_remote_ui_dup (const RUIRemoteUI* self);
void rui_remote_ui_free (RUIRemoteUI* self);
void rui_remote_ui_copy (const RUIRemoteUI* self, RUIRemoteUI* dest);
void rui_remote_ui_destroy (RUIRemoteUI* self);
#define RUI_REMOTE_UI_SERVER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), RUI_TYPE_REMOTE_UI_SERVER, RUIRemoteUIServerPrivate))
enum  {
	RUI_REMOTE_UI_SERVER_DUMMY_PROPERTY
};
#define RUI_REMOTE_UI_SERVER_REMOTE_UI_SERVICE_TYPE "urn:schemas-upnp-org:service:RemoteUIServer:1"
gpointer rui_config_file_reader_ref (gpointer instance);
void rui_config_file_reader_unref (gpointer instance);
GParamSpec* rui_param_spec_config_file_reader (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rui_value_set_config_file_reader (GValue* value, gpointer v_object);
void rui_value_take_config_file_reader (GValue* value, gpointer v_object);
gpointer rui_value_get_config_file_reader (const GValue* value);
GType rui_config_file_reader_get_type (void) G_GNUC_CONST;
RUIRemoteUIServer* rui_remote_ui_server_new (RUIConfigFileReader* config);
RUIRemoteUIServer* rui_remote_ui_server_construct (GType object_type, RUIConfigFileReader* config);
const gchar* rui_config_file_reader_get_root_device_xml (RUIConfigFileReader* self);
const gchar* rui_config_file_reader_get_service_directory (RUIConfigFileReader* self);
GeeCollection* rui_config_file_reader_get_remoteUIs (RUIConfigFileReader* self);
static void rui_remote_ui_server_on_remote_uis_changed (RUIRemoteUIServer* self, RUIConfigFileReader* config, gchar** changed_uis, int changed_uis_length1);
static void _rui_remote_ui_server_on_remote_uis_changed_rui_config_file_reader_remote_uis_changed (RUIConfigFileReader* _sender, gchar** changed_uis, int changed_uis_length1, gpointer self);
XMLBuilder* xml_builder_new (void);
XMLBuilder* xml_builder_construct (GType object_type);
gpointer xml_builder_ref (gpointer instance);
void xml_builder_unref (gpointer instance);
GParamSpec* param_spec_xml_builder (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_xml_builder (GValue* value, gpointer v_object);
void value_take_xml_builder (GValue* value, gpointer v_object);
gpointer value_get_xml_builder (const GValue* value);
GType xml_builder_get_type (void) G_GNUC_CONST;
void xml_builder_append_node (XMLBuilder* self, const gchar* tag, const gchar* content, const gchar* attributes);
gchar* xml_builder_to_string (XMLBuilder* self);
void rui_remote_ui_server_start (RUIRemoteUIServer* self, const gchar* iface, GError** error);
static void rui_remote_ui_server_on_get_compatible_uis (RUIRemoteUIServer* self, GUPnPServiceAction* action);
static void _rui_remote_ui_server_on_get_compatible_uis_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
void xml_builder_open_tag (XMLBuilder* self, const gchar* tag, const gchar* attributes);
void xml_builder_close_tag (XMLBuilder* self, const gchar* tag);
static void rui_remote_ui_server_finalize (RUIRemoteUIServer* obj);


GQuark rui_error_quark (void) {
	return g_quark_from_static_string ("rui_error-quark");
}


static void _rui_remote_ui_server_on_remote_uis_changed_rui_config_file_reader_remote_uis_changed (RUIConfigFileReader* _sender, gchar** changed_uis, int changed_uis_length1, gpointer self) {
	rui_remote_ui_server_on_remote_uis_changed (self, _sender, changed_uis, changed_uis_length1);
}


RUIRemoteUIServer* rui_remote_ui_server_construct (GType object_type, RUIConfigFileReader* config) {
	RUIRemoteUIServer* self = NULL;
	RUIConfigFileReader* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	RUIConfigFileReader* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	RUIConfigFileReader* _tmp8_;
	GeeCollection* _tmp9_;
	GeeCollection* _tmp10_;
	RUIConfigFileReader* _tmp11_;
	g_return_val_if_fail (config != NULL, NULL);
	self = (RUIRemoteUIServer*) g_type_create_instance (object_type);
	_tmp0_ = config;
	_tmp1_ = rui_config_file_reader_get_root_device_xml (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->root_device_xml);
	self->priv->root_device_xml = _tmp3_;
	_tmp4_ = config;
	_tmp5_ = rui_config_file_reader_get_service_directory (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->priv->service_directory);
	self->priv->service_directory = _tmp7_;
	_tmp8_ = config;
	_tmp9_ = rui_config_file_reader_get_remoteUIs (_tmp8_);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (self->priv->remoteUIs);
	self->priv->remoteUIs = _tmp10_;
	_tmp11_ = config;
	g_signal_connect (_tmp11_, "remote-uis-changed", (GCallback) _rui_remote_ui_server_on_remote_uis_changed_rui_config_file_reader_remote_uis_changed, self);
	return self;
}


RUIRemoteUIServer* rui_remote_ui_server_new (RUIConfigFileReader* config) {
	return rui_remote_ui_server_construct (RUI_TYPE_REMOTE_UI_SERVER, config);
}


static void rui_remote_ui_server_on_remote_uis_changed (RUIRemoteUIServer* self, RUIConfigFileReader* config, gchar** changed_uis, int changed_uis_length1) {
	RUIConfigFileReader* _tmp0_;
	GeeCollection* _tmp1_;
	GeeCollection* _tmp2_;
	XMLBuilder* _tmp3_;
	XMLBuilder* builder;
	gchar** _tmp4_;
	gint _tmp4__length1;
	GUPnPService* _tmp8_;
	XMLBuilder* _tmp9_;
	gchar* _tmp10_ = NULL;
	GValue _tmp11_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (config != NULL);
	_tmp0_ = config;
	_tmp1_ = rui_config_file_reader_get_remoteUIs (_tmp0_);
	_tmp2_ = _tmp1_;
	_g_object_unref0 (self->priv->remoteUIs);
	self->priv->remoteUIs = _tmp2_;
	_tmp3_ = xml_builder_new ();
	builder = _tmp3_;
	_tmp4_ = changed_uis;
	_tmp4__length1 = changed_uis_length1;
	{
		gchar** id_collection = NULL;
		gint id_collection_length1 = 0;
		gint _id_collection_size_ = 0;
		gint id_it = 0;
		id_collection = _tmp4_;
		id_collection_length1 = _tmp4__length1;
		for (id_it = 0; id_it < _tmp4__length1; id_it = id_it + 1) {
			gchar* _tmp5_;
			gchar* id = NULL;
			_tmp5_ = g_strdup (id_collection[id_it]);
			id = _tmp5_;
			{
				XMLBuilder* _tmp6_;
				const gchar* _tmp7_;
				_tmp6_ = builder;
				_tmp7_ = id;
				xml_builder_append_node (_tmp6_, "uiID", _tmp7_, NULL);
				_g_free0 (id);
			}
		}
	}
	_tmp8_ = self->priv->service;
	_tmp9_ = builder;
	_tmp10_ = xml_builder_to_string (_tmp9_);
	g_value_init (&_tmp11_, G_TYPE_STRING);
	g_value_take_string (&_tmp11_, _tmp10_);
	gupnp_service_notify_value (_tmp8_, "UIListingUpdate", &_tmp11_);
	G_IS_VALUE (&_tmp11_) ? (g_value_unset (&_tmp11_), NULL) : NULL;
	_xml_builder_unref0 (builder);
}


static void _rui_remote_ui_server_on_get_compatible_uis_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
	rui_remote_ui_server_on_get_compatible_uis (self, action);
}


void rui_remote_ui_server_start (RUIRemoteUIServer* self, const gchar* iface, GError** error) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
	GUPnPContext* _tmp2_;
	GUPnPContext* _tmp3_;
	GUPnPContext* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	GUPnPRootDevice* _tmp7_;
	GUPnPRootDevice* _tmp8_;
	FILE* _tmp9_;
	GUPnPContext* _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	GUPnPContext* _tmp13_;
	guint _tmp14_;
	guint _tmp15_;
	GUPnPRootDevice* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp18_;
	GUPnPRootDevice* _tmp19_;
	GUPnPServiceInfo* _tmp20_ = NULL;
	GUPnPService* _tmp21_;
	GUPnPService* _tmp26_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "RUI.RemoteUIServer.start(iface) called\n");
	_tmp1_ = iface;
	_tmp2_ = gupnp_context_new (NULL, _tmp1_, (guint) 0, &_inner_error_);
	_tmp3_ = _tmp2_;
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	_g_object_unref0 (self->priv->context);
	self->priv->context = _tmp3_;
	_tmp4_ = self->priv->context;
	_tmp5_ = self->priv->root_device_xml;
	_tmp6_ = self->priv->service_directory;
	_tmp7_ = gupnp_root_device_new (_tmp4_, _tmp5_, _tmp6_);
	_g_object_unref0 (self->priv->root_device);
	self->priv->root_device = _tmp7_;
	_tmp8_ = self->priv->root_device;
	gupnp_root_device_set_available (_tmp8_, TRUE);
	_tmp9_ = stdout;
	_tmp10_ = self->priv->context;
	_tmp11_ = gssdp_client_get_host_ip ((GSSDPClient*) _tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = self->priv->context;
	_tmp14_ = gupnp_context_get_port (_tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = self->priv->root_device;
	_tmp17_ = gupnp_root_device_get_description_path (_tmp16_);
	_tmp18_ = _tmp17_;
	fprintf (_tmp9_, "Running UPnP service on http://%s:%u/%s\n", _tmp12_, _tmp15_, _tmp18_);
	_tmp19_ = self->priv->root_device;
	_tmp20_ = gupnp_device_info_get_service ((GUPnPDeviceInfo*) _tmp19_, RUI_REMOTE_UI_SERVER_REMOTE_UI_SERVICE_TYPE);
	_g_object_unref0 (self->priv->service);
	self->priv->service = GUPNP_SERVICE (_tmp20_);
	_tmp21_ = self->priv->service;
	if (_tmp21_ == NULL) {
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_;
		GError* _tmp24_;
		GError* _tmp25_;
		_tmp22_ = g_strdup_printf ("Unable to get %s.", RUI_REMOTE_UI_SERVER_REMOTE_UI_SERVICE_TYPE);
		_tmp23_ = _tmp22_;
		_tmp24_ = g_error_new_literal (RUI_ERROR, RUI_ERROR_BAD_CONFIG, _tmp23_);
		_tmp25_ = _tmp24_;
		_g_free0 (_tmp23_);
		_inner_error_ = _tmp25_;
		g_propagate_error (error, _inner_error_);
		return;
	}
	_tmp26_ = self->priv->service;
	g_signal_connect (_tmp26_, "action-invoked::GetCompatibleUIs", (GCallback) _rui_remote_ui_server_on_get_compatible_uis_gupnp_service_action_invoked, self);
}


static void rui_remote_ui_server_on_get_compatible_uis (RUIRemoteUIServer* self, GUPnPServiceAction* action) {
	XMLBuilder* _tmp0_;
	XMLBuilder* builder;
	XMLBuilder* _tmp1_;
	XMLBuilder* _tmp68_;
	GUPnPServiceAction* _tmp69_;
	XMLBuilder* _tmp70_;
	gchar* _tmp71_ = NULL;
	GValue _tmp72_ = {0};
	GUPnPServiceAction* _tmp73_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (action != NULL);
	_tmp0_ = xml_builder_new ();
	builder = _tmp0_;
	_tmp1_ = builder;
	xml_builder_open_tag (_tmp1_, "uilist", NULL);
	{
		GeeCollection* _tmp2_;
		GeeIterator* _tmp3_ = NULL;
		GeeIterator* _ui_it;
		_tmp2_ = self->priv->remoteUIs;
		_tmp3_ = gee_iterable_iterator ((GeeIterable*) _tmp2_);
		_ui_it = _tmp3_;
		while (TRUE) {
			GeeIterator* _tmp4_;
			gboolean _tmp5_ = FALSE;
			GeeIterator* _tmp6_;
			gpointer _tmp7_ = NULL;
			RUIRemoteUI* _tmp8_;
			RUIRemoteUI _tmp9_ = {0};
			RUIRemoteUI _tmp10_;
			RUIRemoteUI ui;
			XMLBuilder* _tmp11_;
			XMLBuilder* _tmp12_;
			RUIRemoteUI _tmp13_;
			const gchar* _tmp14_;
			XMLBuilder* _tmp15_;
			RUIRemoteUI _tmp16_;
			const gchar* _tmp17_;
			RUIRemoteUI _tmp18_;
			const gchar* _tmp19_;
			gboolean _tmp23_ = FALSE;
			RUIRemoteUI _tmp24_;
			RUIIcon* _tmp25_;
			gint _tmp25__length1;
			gboolean _tmp28_;
			RUIRemoteUI _tmp53_;
			RUIProtocol* _tmp54_;
			gint _tmp54__length1;
			XMLBuilder* _tmp67_;
			_tmp4_ = _ui_it;
			_tmp5_ = gee_iterator_next (_tmp4_);
			if (!_tmp5_) {
				break;
			}
			_tmp6_ = _ui_it;
			_tmp7_ = gee_iterator_get (_tmp6_);
			_tmp8_ = (RUIRemoteUI*) _tmp7_;
			rui_remote_ui_copy (_tmp8_, &_tmp9_);
			_tmp10_ = _tmp9_;
			_rui_remote_ui_free0 (_tmp8_);
			ui = _tmp10_;
			_tmp11_ = builder;
			xml_builder_open_tag (_tmp11_, "ui", NULL);
			_tmp12_ = builder;
			_tmp13_ = ui;
			_tmp14_ = _tmp13_.id;
			xml_builder_append_node (_tmp12_, "uiID", _tmp14_, NULL);
			_tmp15_ = builder;
			_tmp16_ = ui;
			_tmp17_ = _tmp16_.name;
			xml_builder_append_node (_tmp15_, "name", _tmp17_, NULL);
			_tmp18_ = ui;
			_tmp19_ = _tmp18_.description;
			if (_tmp19_ != NULL) {
				XMLBuilder* _tmp20_;
				RUIRemoteUI _tmp21_;
				const gchar* _tmp22_;
				_tmp20_ = builder;
				_tmp21_ = ui;
				_tmp22_ = _tmp21_.description;
				xml_builder_append_node (_tmp20_, "description", _tmp22_, NULL);
			}
			_tmp24_ = ui;
			_tmp25_ = _tmp24_.icons;
			_tmp25__length1 = _tmp24_.icons_length1;
			if (_tmp25_ != NULL) {
				RUIRemoteUI _tmp26_;
				RUIIcon* _tmp27_;
				gint _tmp27__length1;
				_tmp26_ = ui;
				_tmp27_ = _tmp26_.icons;
				_tmp27__length1 = _tmp26_.icons_length1;
				_tmp23_ = _tmp27__length1 > 0;
			} else {
				_tmp23_ = FALSE;
			}
			_tmp28_ = _tmp23_;
			if (_tmp28_) {
				XMLBuilder* _tmp29_;
				RUIRemoteUI _tmp30_;
				RUIIcon* _tmp31_;
				gint _tmp31__length1;
				XMLBuilder* _tmp52_;
				_tmp29_ = builder;
				xml_builder_open_tag (_tmp29_, "iconList", NULL);
				_tmp30_ = ui;
				_tmp31_ = _tmp30_.icons;
				_tmp31__length1 = _tmp30_.icons_length1;
				{
					RUIIcon* icon_collection = NULL;
					gint icon_collection_length1 = 0;
					gint _icon_collection_size_ = 0;
					gint icon_it = 0;
					icon_collection = _tmp31_;
					icon_collection_length1 = _tmp31__length1;
					for (icon_it = 0; icon_it < _tmp31__length1; icon_it = icon_it + 1) {
						RUIIcon _tmp32_ = {0};
						RUIIcon icon = {0};
						rui_icon_copy (&icon_collection[icon_it], &_tmp32_);
						icon = _tmp32_;
						{
							XMLBuilder* _tmp33_;
							XMLBuilder* _tmp34_;
							RUIIcon _tmp35_;
							const gchar* _tmp36_;
							RUIIcon _tmp37_;
							guint64* _tmp38_;
							RUIIcon _tmp44_;
							guint64* _tmp45_;
							XMLBuilder* _tmp51_;
							_tmp33_ = builder;
							xml_builder_open_tag (_tmp33_, "icon", NULL);
							_tmp34_ = builder;
							_tmp35_ = icon;
							_tmp36_ = _tmp35_.url;
							xml_builder_append_node (_tmp34_, "url", _tmp36_, NULL);
							_tmp37_ = icon;
							_tmp38_ = _tmp37_.width;
							if (_tmp38_ != NULL) {
								XMLBuilder* _tmp39_;
								RUIIcon _tmp40_;
								guint64* _tmp41_;
								gchar* _tmp42_ = NULL;
								gchar* _tmp43_;
								_tmp39_ = builder;
								_tmp40_ = icon;
								_tmp41_ = _tmp40_.width;
								_tmp42_ = g_strdup_printf ("%" G_GUINT64_FORMAT, *_tmp41_);
								_tmp43_ = _tmp42_;
								xml_builder_append_node (_tmp39_, "width", _tmp43_, NULL);
								_g_free0 (_tmp43_);
							}
							_tmp44_ = icon;
							_tmp45_ = _tmp44_.height;
							if (_tmp45_ != NULL) {
								XMLBuilder* _tmp46_;
								RUIIcon _tmp47_;
								guint64* _tmp48_;
								gchar* _tmp49_ = NULL;
								gchar* _tmp50_;
								_tmp46_ = builder;
								_tmp47_ = icon;
								_tmp48_ = _tmp47_.height;
								_tmp49_ = g_strdup_printf ("%" G_GUINT64_FORMAT, *_tmp48_);
								_tmp50_ = _tmp49_;
								xml_builder_append_node (_tmp46_, "height", _tmp50_, NULL);
								_g_free0 (_tmp50_);
							}
							_tmp51_ = builder;
							xml_builder_close_tag (_tmp51_, "icon");
							rui_icon_destroy (&icon);
						}
					}
				}
				_tmp52_ = builder;
				xml_builder_close_tag (_tmp52_, "iconList");
			}
			_tmp53_ = ui;
			_tmp54_ = _tmp53_.protocols;
			_tmp54__length1 = _tmp53_.protocols_length1;
			{
				RUIProtocol* protocol_collection = NULL;
				gint protocol_collection_length1 = 0;
				gint _protocol_collection_size_ = 0;
				gint protocol_it = 0;
				protocol_collection = _tmp54_;
				protocol_collection_length1 = _tmp54__length1;
				for (protocol_it = 0; protocol_it < _tmp54__length1; protocol_it = protocol_it + 1) {
					RUIProtocol _tmp55_ = {0};
					RUIProtocol protocol = {0};
					rui_protocol_copy (&protocol_collection[protocol_it], &_tmp55_);
					protocol = _tmp55_;
					{
						XMLBuilder* _tmp56_;
						RUIProtocol _tmp57_;
						const gchar* _tmp58_;
						gchar* _tmp59_ = NULL;
						gchar* _tmp60_;
						RUIProtocol _tmp61_;
						gchar** _tmp62_;
						gint _tmp62__length1;
						XMLBuilder* _tmp66_;
						_tmp56_ = builder;
						_tmp57_ = protocol;
						_tmp58_ = _tmp57_.shortName;
						_tmp59_ = g_strdup_printf ("shortName=\"%s\"", _tmp58_);
						_tmp60_ = _tmp59_;
						xml_builder_open_tag (_tmp56_, "protocol", _tmp60_);
						_g_free0 (_tmp60_);
						_tmp61_ = protocol;
						_tmp62_ = _tmp61_.urls;
						_tmp62__length1 = _tmp61_.urls_length1;
						{
							gchar** url_collection = NULL;
							gint url_collection_length1 = 0;
							gint _url_collection_size_ = 0;
							gint url_it = 0;
							url_collection = _tmp62_;
							url_collection_length1 = _tmp62__length1;
							for (url_it = 0; url_it < _tmp62__length1; url_it = url_it + 1) {
								gchar* _tmp63_;
								gchar* url = NULL;
								_tmp63_ = g_strdup (url_collection[url_it]);
								url = _tmp63_;
								{
									XMLBuilder* _tmp64_;
									const gchar* _tmp65_;
									_tmp64_ = builder;
									_tmp65_ = url;
									xml_builder_append_node (_tmp64_, "uri", _tmp65_, NULL);
									_g_free0 (url);
								}
							}
						}
						_tmp66_ = builder;
						xml_builder_close_tag (_tmp66_, "protocol");
						rui_protocol_destroy (&protocol);
					}
				}
			}
			_tmp67_ = builder;
			xml_builder_close_tag (_tmp67_, "ui");
			rui_remote_ui_destroy (&ui);
		}
		_g_object_unref0 (_ui_it);
	}
	_tmp68_ = builder;
	xml_builder_close_tag (_tmp68_, "uilist");
	_tmp69_ = action;
	_tmp70_ = builder;
	_tmp71_ = xml_builder_to_string (_tmp70_);
	g_value_init (&_tmp72_, G_TYPE_STRING);
	g_value_take_string (&_tmp72_, _tmp71_);
	gupnp_service_action_set_value (_tmp69_, "UIListing", &_tmp72_);
	G_IS_VALUE (&_tmp72_) ? (g_value_unset (&_tmp72_), NULL) : NULL;
	_tmp73_ = action;
	gupnp_service_action_return (_tmp73_);
	_xml_builder_unref0 (builder);
}


static void rui_value_remote_ui_server_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void rui_value_remote_ui_server_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		rui_remote_ui_server_unref (value->data[0].v_pointer);
	}
}


static void rui_value_remote_ui_server_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = rui_remote_ui_server_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer rui_value_remote_ui_server_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* rui_value_remote_ui_server_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		RUIRemoteUIServer* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = rui_remote_ui_server_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* rui_value_remote_ui_server_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	RUIRemoteUIServer** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = rui_remote_ui_server_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* rui_param_spec_remote_ui_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	RUIParamSpecRemoteUIServer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, RUI_TYPE_REMOTE_UI_SERVER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer rui_value_get_remote_ui_server (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_REMOTE_UI_SERVER), NULL);
	return value->data[0].v_pointer;
}


void rui_value_set_remote_ui_server (GValue* value, gpointer v_object) {
	RUIRemoteUIServer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_REMOTE_UI_SERVER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, RUI_TYPE_REMOTE_UI_SERVER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		rui_remote_ui_server_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		rui_remote_ui_server_unref (old);
	}
}


void rui_value_take_remote_ui_server (GValue* value, gpointer v_object) {
	RUIRemoteUIServer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, RUI_TYPE_REMOTE_UI_SERVER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, RUI_TYPE_REMOTE_UI_SERVER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		rui_remote_ui_server_unref (old);
	}
}


static void rui_remote_ui_server_class_init (RUIRemoteUIServerClass * klass) {
	rui_remote_ui_server_parent_class = g_type_class_peek_parent (klass);
	RUI_REMOTE_UI_SERVER_CLASS (klass)->finalize = rui_remote_ui_server_finalize;
	g_type_class_add_private (klass, sizeof (RUIRemoteUIServerPrivate));
}


static void rui_remote_ui_server_instance_init (RUIRemoteUIServer * self) {
	self->priv = RUI_REMOTE_UI_SERVER_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void rui_remote_ui_server_finalize (RUIRemoteUIServer* obj) {
	RUIRemoteUIServer * self;
	self = RUI_REMOTE_UI_SERVER (obj);
	_g_free0 (self->priv->root_device_xml);
	_g_free0 (self->priv->service_directory);
	_g_object_unref0 (self->priv->context);
	_g_object_unref0 (self->priv->root_device);
	_g_object_unref0 (self->priv->service);
	_g_object_unref0 (self->priv->remoteUIs);
}


GType rui_remote_ui_server_get_type (void) {
	static volatile gsize rui_remote_ui_server_type_id__volatile = 0;
	if (g_once_init_enter (&rui_remote_ui_server_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { rui_value_remote_ui_server_init, rui_value_remote_ui_server_free_value, rui_value_remote_ui_server_copy_value, rui_value_remote_ui_server_peek_pointer, "p", rui_value_remote_ui_server_collect_value, "p", rui_value_remote_ui_server_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (RUIRemoteUIServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rui_remote_ui_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RUIRemoteUIServer), 0, (GInstanceInitFunc) rui_remote_ui_server_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType rui_remote_ui_server_type_id;
		rui_remote_ui_server_type_id = g_type_register_fundamental (g_type_fundamental_next (), "RUIRemoteUIServer", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&rui_remote_ui_server_type_id__volatile, rui_remote_ui_server_type_id);
	}
	return rui_remote_ui_server_type_id__volatile;
}


gpointer rui_remote_ui_server_ref (gpointer instance) {
	RUIRemoteUIServer* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void rui_remote_ui_server_unref (gpointer instance) {
	RUIRemoteUIServer* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		RUI_REMOTE_UI_SERVER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



